theme: jekyll-theme-cayman
title: AI Adoption in Pakistan's Public Sector
description: A Comprehensive Research Study
show_downloads: false
github:
  repository_url: https://github.com/arqamxjay/Artificial-Intelligence-Adoption-in-Pakistan-s-Public-Sector-A-Comprehensive-Research-
